### ISSUE TITLE
In game network

### ISSUE THREAD

**Issue by tistech0** [VictorHarri-Chal/R-Type#123]
Communicate data to enable gameplay. Receive player-related commands and update data accordingly.
Create the game loop with sending commands.

**Comment by simlf** [comment]
**Client :**
- [X] Send in game data (e.g. shoot, move) from Clients to Server
- [ ] Remove all the ECS logic except for the ```Draw```
- [ ] Update drawable objects with the informations received by the server

**Server:**
- [ ] Create the main gameLoop on the server
- [ ] The loop should be receiving the clients *events* (the movement/shoots of the players)
- [ ] The loop should run the game with the ECS so that we can get the position of every entities
- [ ] The loop should send to each clients the corresponding informations (the movement/shoots of the enemis, the movement/shoot of the players)
